version: '2.1'
services:
  mysql:
    container_name: mysql
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ~/docker/mysql/sql:/sql
      - ~/docker/mysql/conf/my.cnf:/etc/my.cnf
      - ~/docker/mysql/data:/var/lib/mysql
      - ~/docker/mysql/logs:/var/log/mysql
      - ~/docker/mysql/mysql-files:/var/lib/mysql-files
    environment:
      - MYSQL_ROOT_PASSWORD=root
    #command: 
      #--max_connections=1000
      #--character-set-server=utf8mb4
      #--collation-server=utf8mb4_general_ci
      #--default-authentication-plugin=mysql_native_password
      #--lower_case_table_names=1
    image: mysql
    user: root
  redis:
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    volumes:
      - ~/docker/redis/data:/data
      - ~/docker/redis/conf/redis.conf:/etc/redis/redis.conf
    image: redis
    command: "/etc/redis/redis.conf --requirepass root --appendonly yes"

  nginx:
    container_name: nginx
    ports:
      - "80:80"
    restart: always
    volumes:
      - ~/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ~/docker/nginx/html:/usr/share/nginx/html
      - ~/docker/nginx/logs:/var/log/nginx
      - ~/docker/nginx/conf.d:/etc/nginx/conf.d
    image: nginx:stable

  elasticsearch:
    container_name: elasticsearch
    restart: always
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - ~/docker/es/config:/usr/share/elasticsearch/config
      - ~/docker/es/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ~/docker/es/data/:/usr/share/elasticsearch/data
      - ~/docker/es/plugins:/usr/share/elasticsearch/plugins
    healthcheck:
      test: ["CMD", "curl", "-u", "elastic:your_password_here", "-f", "http://elasticsearch:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.1

  kibana:
    container_name: kibana
    restart: always
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    volumes:
      - ~/docker/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    image: kibana:8.15.1
  rabbitmq:
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    restart: always
    volumes:
      - ~/docker/rabbitmq/data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    image: rabbitmq:management

  nacos:
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
    restart: always
    depends_on:
      - mysql
    environment:
      - MODE=standalone
      - PREFER_HOST_MODE=ip
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_DATABASE_NUM=1
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    volumes:
      - ~/docker/nacos/logs:/home/nacos/logs
      - ~/docker/nacos/conf:/home/nacos/conf
      - ~/docker/nacos/bin:/home/nacos/bin
    image: nacos/nacos-server:latest

  sentinel:
    container_name: sentinel
    ports:
      - "8858:8858"
    restart: always
    image: bladex/sentinel-dashboard:latest

  zipkin:
    container_name: zipkin
    ports:
      - "9411:9411"
    restart: always
    depends_on:
      elasticsearch:
         condition: service_healthy
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
      - ES_USERNAME=elastic
      - ES_PASSWORD=elastic
      - RABBIT_ADDRESSES=rabbitmq
      - RABBIT_PASSWORD=root
      - RABBIT_USER=root
    image: ghcr.io/openzipkin/zipkin:latest
  dependencies:
    image: ghcr.io/openzipkin/zipkin-dependencies
    container_name: dependencies
    user: root
    entrypoint: /usr/sbin/crond -f
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch
      - ZIPKIN_LOG_LEVEL=DEBUG