spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment} #该处填product的路径名
        - id: third_party_route
          uri: lb://third
          predicates:
            - Path=/api/third/**
          filters:
            - RewritePath=/api/third/(?<segment>.*),/$\{segment} #该处填third的路径名
        - id: member_route
          uri: lb://member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment} #该处填member的路径名
        - id: member_route
          uri: lb://ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment} #该处填ware的路径名
        - id: admin_route
          uri: lb://fast # 该处填nacos上的服务名(即spring.application.name中的值)
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #该处填renren-fast的路径名
    # 使用spring loadbalancer，弃用ribbon
    loadbalancer:
      ribbon:
        enabled: false
