spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://product
          predicates:
            - Path=/api/product/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment} #该处填renren-fast的路径名
        - id: admin_route
          uri: lb://fast # 该处填nacos上的服务名(即spring.application.name中的值)
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment} #该处填renren-fast的路径名
    # 使用spring loadbalancer，弃用ribbon
    loadbalancer:
      ribbon:
        enabled: false
